using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Xml;
using System.Collections.Generic;

namespace LinqXML
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
           
        }



        protected void cmdCreateXml_Click1(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"D:\Trabajadores.xml", FileMode.Create);
            XmlTextWriter w = new XmlTextWriter(fs, null);
            w.WriteStartDocument();
            w.WriteStartElement("Trabajadores");
            w.WriteComment("This file generated by the XmlTextWriter class.");
            // Write the first product.
            w.WriteStartElement("Product");
            w.WriteAttributeString("ID", "", "10029");
            w.WriteAttributeString("Name", "", "Josue Butron");
            w.WriteAttributeString("Area", "", "Soporte");
            w.WriteStartElement("Sueldo");
            w.WriteString("3000.00");
            w.WriteEndElement();
            w.WriteEndElement();
            // Write the second product
            w.WriteStartElement("Product");
            w.WriteAttributeString("ID", "", "20001");
            w.WriteAttributeString("Name", "", "Gonzalo Urrutia");
            w.WriteAttributeString("Area", "", "Manteniemiento");
            w.WriteStartElement("Sueldo");
            w.WriteString("4000.00");
            w.WriteEndElement();
            w.WriteEndElement();
            // Write the third product.
            w.WriteStartElement("Product");
            w.WriteAttributeString("ID", "", "30002");
            w.WriteAttributeString("Name", "", "Pepe Zaldivar");
            w.WriteAttributeString("Area", "", "Gerencia");
            w.WriteStartElement("Sueldo");
            w.WriteString("10000.00");
            w.WriteEndElement();
            w.WriteEndElement();
            //Close the root element.
            w.WriteEndElement();
            w.WriteEndDocument();
            w.Close();

            lblXml.Text = @"File os\SuperProProductList.xml written successfully.";

        }

        protected void cmdReadXml_Click1(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"D:\Trabajadores.xml", FileMode.Open);
            XmlTextReader r = new XmlTextReader(fs);
            // Store the whole file in a StringWriter(much quicker than using
            // string operations)
            StringWriter writer = new StringWriter();
            // Parse the file and read each node
            while (r.Read())
            {
                writer.Write("<b>Type:</b>");
                writer.Write(r.NodeType.ToString());
                writer.Write("<br>");
            }

            if (r.Name != "")
            {
                writer.Write("<b>Name:</b>");
                writer.Write(r.Name);
                writer.Write("<br>");
            }
            if (r.Value != "")
            {
                writer.Write("<b›Value:</b>");
                writer.Write(r.Value);
                writer.Write("<br>");
            }

            if (r.AttributeCount > 0)
            {
                writer.Write("<b>Attributes:</b>");
                for (int i = 0; i < r.AttributeCount; i++)
                {
                    writer.Write(" ");
                    writer.Write(r.GetAttribute(i));
                    writer.Write(" ");
                }
                writer.Write("<br>");
            }
            writer.Write("<br>");
            r.Close();
            lblXml.Text = writer.ToString();
        }

        protected void cdmReadXmlAsObjects_Click1(object sender, EventArgs e)
        {
            // Open a stream to the file.
            FileStream fs = new FileStream(@"D:\Trabajadores.xml", FileMode.Open);
            XmlTextReader r = new XmlTextReader(fs);
            // Create a generic collection of products.
            List<Product> products = new List<Product>();
            // Loop through the products
            while (r.Read())
            {
                if (r.NodeType == XmlNodeType.Element && r.Name == "Product")
                {
                    Product newProduct = new Product();
                    newProduct.ID = Int32.Parse(r.GetAttribute(0));
                    newProduct.Name = r.GetAttribute(1);
                    newProduct.Area = r.GetAttribute(2);
                    
                    while (r.NodeType != XmlNodeType.EndElement)
                    {
                        r.Read();
                        if (r.Name == "Sueldo")
                        {
                            while (r.NodeType == XmlNodeType.Text)
                            {
                                r.Read();
                                if (r.NodeType == XmlNodeType.Text)
                                {
                                    newProduct.Sueldo = Decimal.Parse(r.Value);
                                }
                            }
                        }
                    }
                    products.Add(newProduct);
                }
            }
            r.Close();

            gridResults.DataSource = products;
            gridResults.DataBind();
        }
    }
}
